script:
    log_file_name: NHLTwitterBot
    event_timeout: 300
    preview_sleep_time: 1800
    pregame_sleep_time: 15
    live_sleep_time: 4
    intermission_sleep_time: 60
    final_sleep_time: 10

default:
    team_name: Calgary Flames

socials:
    twitter: False
    discord: True
    slack: False

twitter:
    prod:
        consumer_key: XXX
        consumer_secret: XXX
        access_token: XXX
        access_secret: XXX
        handle: XXX
    debug:
        consumer_key: XXX
        consumer_secret: XXX
        access_token: XXX
        access_secret: XXX
        handle: XXX

discord:
    prod:
        webhook_url: https://discord.com/api/webhooks/1427843112364937226/EYw7XzKji4zj3B916oHJHdJNe-PusUMUqItiOF6cOJBLJ1RodTVP1Hl89Oewikc-H--3
    debug:
        webhook_url: https://discord.com/api/webhooks/1427843112364937226/EYw7XzKji4zj3B916oHJHdJNe-PusUMUqItiOF6cOJBLJ1RodTVP1Hl89Oewikc-H--3
